service: tune-the-tune

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs10.16
  region: us-east-1

functions:
  signUpForm:
    handler: src/signUpForm/signUpForm.default
    events:
      - http:
          path: /sign-up
          method: post
